version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sport-event-finder-db
    ports:
      - "5432:5432"
    volumes:
      - ./sport-event-finder-data:/var/lib/postgresql/data

  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"
    environment:
      SPRING_APPLICATION_NAME: discovery-server
      EUREKA_INSTANCE_HOSTNAME: discovery-server
      EUREKA_CLIENT_REGISTER-WITH-EUREKA: "false"
      EUREKA_CLIENT_FETCH-REGISTRY: "false"
    depends_on:
      - db

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
      - "5000:5000"
    environment:
      SPRING_APPLICATION_NAME: api-gateway
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5000"
    depends_on:
      - discovery-server
      - auth-server
      - user-service
      - sport-event-service

  auth-server:
    build: ./auth-server
    ports:
      - "8001:8001"
      - "5001:5001"
    environment:
      SPRING_APPLICATION_NAME: auth-server
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5001"
    depends_on:
      - discovery-server
      - user-service

  user-service:
    build: ./user-service
    ports:
      - "8002:8002"
      - "5002:5002"
    environment:
      SPRING_APPLICATION_NAME: user-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sport-event-finder-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5002"
    depends_on:
      - db
      - discovery-server
    restart: on-failure

  sport-event-service:
    build: ./sport-event-service
    ports:
      - "8003:8003"
      - "5003:5003"
    environment:
      SPRING_APPLICATION_NAME: sport-event-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sport-event-finder-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5003"
    depends_on:
      - db
      - discovery-server
    restart: on-failure


