version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sport-event-finder-db
    ports:
      - "5432:5432"
    volumes:
      - ./sport-event-finder-data:/var/lib/postgresql/data

  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"
    environment:
      SPRING_APPLICATION_NAME: discovery-server
      EUREKA_INSTANCE_HOSTNAME: discovery-server
      EUREKA_CLIENT_REGISTER-WITH-EUREKA: "false"
      EUREKA_CLIENT_FETCH-REGISTRY: "false"
    depends_on:
      - db

  auth-server:
    build: ./auth-server
    ports:
      - "8001:8001"
    environment:
      SPRING_APPLICATION_NAME: auth-server
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server

  user-service:
    build: ./user-service
    ports:
      - "8002:8002"
    environment:
      SPRING_APPLICATION_NAME: user-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sport-event-finder-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    depends_on:
      - db
      - discovery-server
    restart: on-failure

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    environment:
      SPRING_APPLICATION_NAME: api-gateway
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
      - auth-server
      - user-service
